Seen phrase
onja-org/malagasy-rn-Polonium pull request #8
Opened 2021-05-25 11:45 UTC by mitia-anah

Hello team!

The seen phrases is done, so you can have a look at it. Happy to see your comment.
Thanks

2021-05-26 06:00 UTC, Fodilahy-mena commented on src/screens/Home.js
> +            data={[{ id: 1, name: seenPhrasesTotal() }]}
instead of id: 2 use something like id: ###seen-phrases### just for consistency.

2021-05-26 06:05 UTC, Fodilahy-mena commented on src/screens/Home.js
> +            data={[{ id: 1, name: seenPhrasesTotal() }]}
the commit message `adds csome chsnges` should be changed. [See here on how to change commit messages](https://linuxize.com/post/change-git-commit-message/)

2021-05-26 06:13 UTC, Fodilahy-mena commented on src/screens/Home.js
> +            data={[{ id: 1, name: seenPhrasesTotal() }]}
the commit message `adds csome chsnges` should be changed. [See here on how to change commit messages](https://linuxize.com/post/change-git-commit-message/)

2021-05-26 11:31 UTC, andrzej-onja requested changes

2021-05-26 11:31 UTC, andrzej-onja commented on package.json
> +    "redux-persist": "^6.0.0",
Do you need that ?

2021-05-26 11:31 UTC, andrzej-onja commented on src/screens/Learning.js
> +        );
move this logic inside `removeFromSeenPhrases` action and as a payload pass just `item`

2021-05-26 11:31 UTC, andrzej-onja commented on src/redux/actions/index.js
> +export function removeFromSeenPhrases(seenPhrases) {
rename seenPhrase_s_ to seenPhrase

2021-05-26 11:31 UTC, andrzej-onja commented on src/redux/reducers/index.js
> +      return action.payload;
all of the above can be replaced with SET_SEEN_PHRASE as it does the same

2021-05-26 11:31 UTC, andrzej-onja commented on src/containers/LearningScreenContainer.js
> +    isSeenPhrases: isSeenPhrases(state),
this is unecessary

2021-05-26 11:31 UTC, andrzej-onja commented on src/redux/reducers/index.js
> +      return action.payload;
delete REMOVE_FROM_SEEN_PHRASES and SEEN_PHRASES_KEY they can be just replaced by SET_SEEN_PHRASE

2021-05-26 11:31 UTC, andrzej-onja commented on src/redux/constants/index.js
> +export const SEEN_PHRASES_KEY = 'SEEN_PHRASES_KEY';
SEEN_PHRASES_KEY should be stored in the `src/utils/storage.js `

2021-05-26 11:31 UTC, andrzej-onja commented on src/redux/selectors/index.js
> +
Nice use of selector!

2021-05-26 11:31 UTC, andrzej-onja commented on src/screens/Home.js
> +    setPhrases(phrasesForCategory);
Conflict resolving mistake ?
`
const phrasesForCategory = getPhrasesForCategoryId(item.id);
    setPhrases(phrasesForCategory)
`
is duplicated

2021-05-26 11:31 UTC, andrzej-onja commented on src/screens/Learning.js
>      [currentPhrase, setDisableAllOptions, answerOptions],
seenPhrases has to be added to dependency array
[currentPhrase, setDisableAllOptions, answerOptions, seenPhrases]

2021-05-26 11:31 UTC, andrzej-onja commented on yarn.lock
> +=======
There are some leftovers from rebasing 
<<<<<<< HEAD
=======

2021-06-04 12:21 UTC, constantingoeldel commented on src/containers/HomeScreenContainer.js
> +  setSeenPhrases,
Why does the homescreen need this?

2021-06-07 06:54 UTC, andrzej-onja approved these changes

2021-06-07 06:54 UTC, andrzej-onja commented on src/redux/actions/index.js
>    };
Lets rewrite it this way:
 
   ```
    const storedSeenPhrases = await getDataFromStorage(SEEN_PHRASES_KEY);
    if (storedSeenPhrases) {
      dispatch(setSeenPhrases(storedSeenPhrases));
    }
    
    return Promise.resolve();
```

2021-06-07 06:54 UTC, andrzej-onja commented on src/redux/reducers/index.js
> +      return action.payload;
delete REMOVE_FROM_SEEN_PHRASES

2021-06-07 07:58 UTC, Fodilahy-mena approved these changes

2021-06-07 12:36 UTC, ganamavo approved these changes

2021-06-08 04:15 UTC, merged